
// This file was auto-generated by ML.NET Model Builder. 

using MLModel2_ConsoleApp4;

// Create single instance of sample data from first line of dataset for model input
MLModel2.ModelInput sampleData = new MLModel2.ModelInput()
{
    Age = 28F,
    Experience = 3F,
    Education = @"Bachelor",
    Skills = @"C#;JavaScript;SQL",
    Gender = @"Male",
    EmployementType = @"Full-time",
    Country = @"USA",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Salary with predicted Salary from sample data...\n\n");


Console.WriteLine($"Age: {28F}");
Console.WriteLine($"Experience: {3F}");
Console.WriteLine($"Education: {@"Bachelor"}");
Console.WriteLine($"Skills: {@"C#;JavaScript;SQL"}");
Console.WriteLine($"Gender: {@"Male"}");
Console.WriteLine($"EmployementType: {@"Full-time"}");
Console.WriteLine($"Country: {@"USA"}");
Console.WriteLine($"Salary: {65000F}");


// Make a single prediction on the sample data and print results
var predictionResult = MLModel2.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Salary: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

