
// This file was auto-generated by ML.NET Model Builder. 

using MLModel2_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel2.ModelInput sampleData = new MLModel2.ModelInput()
{
    Id = 4F,
    FullName = @"firdawok ayele",
    Gender = @"Male",
    Skills = @"Java",
    EmployementType = @"Part-time",
    PhoneNumber = @"0977294591",
    Country = @"Antarctica",
    Age = 29F,
    Education = @"Bachelor of Computer Science (BSc CS)",
    Experience = 5F,
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Salary with predicted Salary from sample data...\n\n");


Console.WriteLine($"Id: {4F}");
Console.WriteLine($"FullName: {@"firdawok ayele"}");
Console.WriteLine($"Gender: {@"Male"}");
Console.WriteLine($"Skills: {@"Java"}");
Console.WriteLine($"EmployementType: {@"Part-time"}");
Console.WriteLine($"PhoneNumber: {@"0977294591"}");
Console.WriteLine($"Country: {@"Antarctica"}");
Console.WriteLine($"Age: {29F}");
Console.WriteLine($"Education: {@"Bachelor of Computer Science (BSc CS)"}");
Console.WriteLine($"Experience: {5F}");


// Make a single prediction on the sample data and print results
var predictionResult = MLModel2.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Salary: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

