
// This file was auto-generated by ML.NET Model Builder. 

using MLModel3_ConsoleApp1;

// Create single instance of sample data from first line of dataset for model input
MLModel3.ModelInput sampleData = new MLModel3.ModelInput()
{
    Age = 32F,
    Experience = 7F,
    Education = @"Master",
    Skills = @"Backend",
    Gender = @"Female",
    EmployementType = @"Full-time",
    Country = @"USA",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Salary with predicted Salary from sample data...\n\n");


Console.WriteLine($"Age: {32F}");
Console.WriteLine($"Experience: {7F}");
Console.WriteLine($"Education: {@"Master"}");
Console.WriteLine($"Skills: {@"Backend"}");
Console.WriteLine($"Gender: {@"Female"}");
Console.WriteLine($"EmployementType: {@"Full-time"}");
Console.WriteLine($"Country: {@"USA"}");
Console.WriteLine($"Salary: {95000F}");


// Make a single prediction on the sample data and print results
var predictionResult = MLModel3.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Salary: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

