
// This file was auto-generated by ML.NET Model Builder. 

using MLModel2_ConsoleAppfin1;

// Create single instance of sample data from first line of dataset for model input
MLModel2.ModelInput sampleData = new MLModel2.ModelInput()
{
    Age = 44F,
    Experience = 18F,
    Education = @"PhD",
    Skills = @"Fullstack",
    Gender = @"Female",
    EmployementType = @"Full-time",
    Country = @"USA",
};



Console.WriteLine("Using model to make single prediction -- Comparing actual Salary with predicted Salary from sample data...\n\n");


Console.WriteLine($"Age: {44F}");
Console.WriteLine($"Experience: {18F}");
Console.WriteLine($"Education: {@"PhD"}");
Console.WriteLine($"Skills: {@"Cloud"}");
Console.WriteLine($"Gender: {@"Female"}");
Console.WriteLine($"EmployementType: {@"Full-time"}");
Console.WriteLine($"Country: {@"USA"}");
Console.WriteLine($"Salary: {95000F}");


// Make a single prediction on the sample data and print results
var predictionResult = MLModel2.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Salary: {predictionResult.Score}\n\n");

Console.WriteLine("=============== End of process, hit any key to finish ===============");
Console.ReadKey();

